package com.joshuahalvorson.datenight.util

class RestaurantCategories {
    companion object {
        val RESTAURANT_CATEGORIES_TITLES = listOf(
            "Afghan",
            "African",
            "American New",
            "American Traditional",
            "Andalusian",
            "Arabian",
            "Argentine",
            "Armenian",
            "Asian Fusion",
            "Asturian",
            "Australian",
            "Austrian",
            "Baguettes",
            "Bangladeshi",
            "Barbeque",
            "Basque",
            "Bavarian",
            "Beer Garden",
            "Beer Hall",
            "Beisl",
            "Belgian",
            "Bistros",
            "Black Sea",
            "Brasseries",
            "Brazilian",
            "Breakfast & Brunch",
            "British",
            "Buffets",
            "Bulgarian",
            "Burgers",
            "Burmese",
            "Cafes",
            "Cafeteria",
            "Cajun/Creole",
            "Cambodian",
            "Canadian New",
            "Canteen",
            "Caribbean",
            "Catalan",
            "Cheesesteaks",
            "Chicken Shop",
            "Chicken Wings",
            "Chilean",
            "Chinese",
            "Comfort Food",
            "Corsican",
            "Creperies",
            "Cuban",
            "Curry Sausage",
            "Cypriot",
            "Czech",
            "Czech/Slovakian",
            "Danish",
            "Delis",
            "Diners",
            "Dinner Theater",
            "Dumplings",
            "Eastern European",
            "Eritrean",
            "Ethiopian",
            "Fast Food",
            "Filipino",
            "Fischbroetchen",
            "Fish & Chips",
            "Flatbread",
            "Fondue",
            "Food Court",
            "Food Stands",
            "Freiduria",
            "French",
            "French Southwest",
            "Galician",
            "Game Meat",
            "Gastropubs",
            "Georgian",
            "German",
            "Giblets",
            "Gluten-Free",
            "Greek",
            "Guamanian",
            "Halal",
            "Hawaiian",
            "Heuriger",
            "Himalayan/Nepalese",
            "Honduran",
            "Hong Kong Style Cafe",
            "Hot Dogs",
            "Hot Pot",
            "Hungarian",
            "Iberian",
            "Indian",
            "Indonesian",
            "International",
            "Irish",
            "Island Pub",
            "Israeli",
            "Italian",
            "Japanese",
            "Jewish",
            "Kebab",
            "Kopitiam",
            "Korean",
            "Kosher",
            "Kurdish",
            "Laos",
            "Laotian",
            "Latin American",
            "Live/Raw Food",
            "Lyonnais",
            "Malaysian",
            "Meatballs",
            "Mediterranean",
            "Mexican",
            "Middle Eastern",
            "Milk Bars",
            "Modern Australian",
            "Modern European",
            "Mongolian",
            "Moroccan",
            "New Mexican Cuisine",
            "New Zealand",
            "Nicaraguan",
            "Night Food",
            "Nikkei",
            "Noodles",
            "Norcinerie",
            "Open Sandwiches",
            "Oriental",
            "PF/Comercial",
            "Pakistani",
            "Pan Asian",
            "Parent Cafes",
            "Parma",
            "Persian/Iranian",
            "Peruvian",
            "Pita",
            "Pizza",
            "Polish",
            "Polynesian",
            "Pop-Up Restaurants",
            "Portuguese",
            "Potatoes",
            "Poutineries",
            "Pub Food",
            "Rice",
            "Romanian",
            "Rotisserie Chicken",
            "Russian",
            "Salad",
            "Sandwiches",
            "Scandinavian",
            "Schnitzel",
            "Scottish",
            "Seafood",
            "Serbo Croatian",
            "Signature Cuisine",
            "Singaporean",
            "Slovakian",
            "Somali",
            "Soul Food",
            "Soup",
            "Southern",
            "Spanish",
            "Sri Lankan",
            "Steakhouses",
            "Supper Clubs",
            "Sushi Bars",
            "Swabian",
            "Swedish",
            "Swiss Food",
            "Syrian",
            "Tabernas",
            "Taiwanese",
            "Tapas Bars",
            "Tapas/Small Plates",
            "Tavola Calda",
            "Tex-Mex",
            "Thai",
            "Traditional Norwegian",
            "Traditional Swedish",
            "Trattorie",
            "Turkish",
            "Ukrainian",
            "Uzbek",
            "Vegan",
            "Vegetarian",
            "Venison",
            "Vietnamese",
            "Waffles",
            "Wok",
            "Wraps",
            "Yugoslav"
        )

        val RESTAURANT_CATEGORIES_CODES = listOf(
            "afghani",
            "african",
            "newamerican",
            "tradamerican",
            "andalusian",
            "arabian",
            "argentine",
            "armenian",
            "asianfusion",
            "asturian",
            "australian",
            "austrian",
            "baguettes",
            "bangladeshi",
            "bbq",
            "basque",
            "bavarian",
            "beergarden",
            "beerhall",
            "beisl",
            "belgian",
            "bistros",
            "blacksea",
            "brasseries",
            "brazilian",
            "breakfast_brunch",
            "british",
            "buffets",
            "bulgarian",
            "burgers",
            "burmese",
            "cafes",
            "cafeteria",
            "cajun",
            "cambodian",
            "newcanadian",
            "canteen",
            "caribbean",
            "catalan",
            "cheesesteaks",
            "chickenshop",
            "chicken_wings",
            "chilean",
            "chinese",
            "comfortfood",
            "corsican",
            "creperies",
            "cuban",
            "currysausage",
            "cypriot",
            "czech",
            "czechslovakian",
            "danish",
            "delis",
            "diners",
            "dinnertheater",
            "dumplings",
            "eastern_european",
            "eritrean",
            "ethiopian",
            "hotdogs",
            "filipino",
            "fischbroetchen",
            "fishnchips",
            "flatbread",
            "fondue",
            "food_court",
            "foodstands",
            "freiduria",
            "french",
            "sud_ouest",
            "galician",
            "gamemeat",
            "gastropubs",
            "georgian",
            "german",
            "giblets",
            "gluten_free",
            "greek",
            "guamanian",
            "halal",
            "hawaiian",
            "heuriger",
            "himalayan",
            "honduran",
            "hkcafe",
            "hotdog",
            "hotpot",
            "hungarian",
            "iberian",
            "indpak",
            "indonesian",
            "international",
            "irish",
            "island_pub",
            "israeli",
            "italian",
            "japanese",
            "jewish",
            "kebab",
            "kopitiam",
            "korean",
            "kosher",
            "kurdish",
            "laos",
            "laotian",
            "latin",
            "raw_food",
            "lyonnais",
            "malaysian",
            "meatballs",
            "mediterranean",
            "mexican",
            "mideastern",
            "milkbars",
            "modern_australian",
            "modern_european",
            "mongolian",
            "moroccan",
            "newmexican",
            "newzealand",
            "nicaraguan",
            "nightfood",
            "nikkei",
            "noodles",
            "norcinerie",
            "opensandwiches",
            "oriental",
            "pfcomercial",
            "pakistani",
            "panasian",
            "eltern_cafes",
            "parma",
            "persian",
            "peruvian",
            "pita",
            "pizza",
            "polish",
            "polynesian",
            "popuprestaurants",
            "portuguese",
            "potatoes",
            "poutineries",
            "pubfood",
            "riceshop",
            "romanian",
            "rotisserie_chicken",
            "russian",
            "salad",
            "sandwiches",
            "scandinavian",
            "schnitzel",
            "scottish",
            "seafood",
            "serbocroatian",
            "signature_cuisine",
            "singaporean",
            "slovakian",
            "somali",
            "soulfood",
            "soup",
            "southern",
            "spanish",
            "srilankan",
            "steak",
            "supperclubs",
            "sushi",
            "swabian",
            "swedish",
            "swissfood",
            "syrian",
            "tabernas",
            "taiwanese",
            "tapas",
            "tapasmallplates",
            "tavolacalda",
            "tex-mex",
            "thai",
            "norwegian",
            "traditional_swedish",
            "trattorie",
            "turkish",
            "ukrainian",
            "uzbek",
            "vegan",
            "vegetarian",
            "venison",
            "vietnamese",
            "waffles",
            "wok",
            "wraps",
            "yugoslav"
        )
    }
}